#!/bin/bash

# cd to qapps dir
top=$(git rev-parse --show-toplevel)
cd $top/qapps

# remove and recreate files dir
run "tar --exclude log -cf -  ." > /tmp/xfer.tar
rm -rf files; mkdir files; cd files
tar -xvf /tmp/xfer.tar
rm /tmp/xfer.tar

# success
exit 0
