#!/bin/bash

filename=file.c
phone_ip_addr=192.168.1.243 
port=1234

if [ "$filename" = "" ]; then
  echo "ERROR filename expected"
  exit 1
fi

if [ ! -f "$filename" ]; then
  echo "ERROR $filename does not exit"
  exit 1
fi

nc $phone_ip_addr $port -N << EOF
password=none cmd=file_put arg1=$filename
$(cat $filename)
EOF

