#!/bin/bash

filename=$1
phone_ip_addr=192.168.1.243 
port=1234

if [ "$filename" = "" ]; then
  echo "ERROR filename expected"
  exit 1
fi

nc $phone_ip_addr $port -N << EOF
password=none cmd=file_rm arg1=$filename
EOF

