#!/bin/bash

do_put_cmd()
{
  nc $phone_ip_addr $port -N << EOF
qne $password $cmd $filename
$(cat $filename)
EOF
}

do_logcat_cmd()
{
  while true; do
    nc $phone_ip_addr $port -N << EOF
qne $password $cmd
EOF
    sleep 2
  done
}

#  -----------------  MAIN-----------------------------------

phone_ip_addr=192.168.1.243 
port=1234
password=none

cmd=$1
filename=$2

# verify supplied cmd is supported
if [ "$cmd" != put -a \
     "$cmd" != get -a \
     "$cmd" != rm  -a \
     "$cmd" != ls  -a \
     "$cmd" != logcat ]
then
  echo "USAGE:"
  echo "  put <filename>"
  echo "  get <filename>"
  echo "  rm <filename>"
  echo "  ls"
  echo "  logcat"
  exit 1
fi

# verify filename is provided, for put, get, and rm cmds
if [ \( "$cmd" = put -o "$cmd" = get -o "$cmd" = rm \) -a "$filename" = "" ]; then
  echo "ERROR: filename expected"
  exit 1
fi

# put cmd
if [ "$cmd" = put ]; then
  do_put_cmd
  exit 0
fi

# logcat cmd
if [ "$cmd" = logcat ]; then
  do_logcat_cmd
  exit 0
fi

# all other cmds
nc $phone_ip_addr $port -N << EOF
qne $password $cmd $filename
EOF

