#ifndef __LOCATION_H__
#define __LOCATION_H__

#define SVC_LOCATION_REQ_GET_LOC_INFO           10
#define SVC_LOCATION_REQ_COUNTRY_INFO_DOWNLOAD  11
#define SVC_LOCATION_REQ_COUNTRY_INFO_DELETE    12
#define SVC_LOCATION_REQ_COUNTRY_INFO_LIST      13

#endif
