#!/bin/bash

# remove and reconstruct assets/apps.tar
rm -f assets/apps.tar
tar -cf assets/apps.tar --exclude-ignore-recursive=tar_exclude_list -C .. apps

# construct version, and rebuild
cd SDL/build/org.sthaid.ezApp
echo "char *version = \"`git log -1 --format=%h`\";" > app/jni/src/version.c
./gradlew assembleDebug

