#!/bin/bash

# remove and reconstruct assets/apps.tar
gen_apps_tar android/assets/apps.tar

# construct version info
../tools/gen_version

# rebuild
cd SDL/build/org.sthaid.ezApp
./gradlew assembleDebug

