#!/bin/bash

#
# Notes:
# - to list the keystore contents:
#     keytool -list -v -keystore ezApp.keystore
#

if [ -e ezApp.keystore ]; then
  echo "*** ERROR ezApp.keystore exists ***"
  exit 1
fi

keytool -genkey -v -keystore ezApp.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias ezApp

