#!/bin/bash

update_build_file()
{
  src=$1
  dest=$2

  echo "- updating $src to $dest"
  if [ -f "$BUILD_DIR/$dest" ]; then
    cp $BUILD_DIR/$dest $TOP/setup_files/orig/${src}
  fi
  ln -sf $TOP/setup_files/${src} $BUILD_DIR/$dest 
}

# ######### MAIN ##########

# init variables
PACKAGE_NAME=org.sthaid.ezApp
SDL_VER=3.2.20
SDL_TTF_VER=3.2.2

# directories
TOP=`pwd`
SDL_DIR=$TOP/SDL3-$SDL_VER
SDL_TTF_DIR=$SDL_DIR/build/$PACKAGE_NAME/app/jni/SDL3_ttf-$SDL_TTF_VER
BUILD_DIR=$SDL_DIR/build/$PACKAGE_NAME
RES_DIR=$BUILD_DIR/app/src/main/res

# sdl 
SDL_TAR_FILE=SDL3-$SDL_VER.tar.gz
SDL_URL=https://github.com/libsdl-org/SDL/releases/download/release-$SDL_VER/$SDL_TAR_FILE

# sdl_ttf
SDL_TTF_TAR_FILE=SDL3_ttf-$SDL_TTF_VER.tar.gz
SDL_TTF_URL=https://www.libsdl.org/projects/SDL_ttf/release/$SDL_TTF_TAR_FILE

# remove existing SDL directory tree, and setup_files/orig
echo "Remove existing $SDL_DIR and setup_files/orig"
rm -rf $SDL_DIR
rm -f SDL
rm -rf setup_files/orig

# if SDL src tar files are not in the setup_files dir, then download them
if [ ! -f setup_files/$SDL_TAR_FILE -o ! -f setup_files/$SDL_TTF_TAR_FILE ]; then
  echo "Downloading SDL3 source tar files"
  cd setup_files
  rm -f *.tar.gz
  wget $SDL_URL
  wget $SDL_TTF_URL
  cd ..
fi

# extract the SDL3 src from tar file
echo "Extracting $SDL_TAR_FILE"
tar -xf setup_files/$SDL_TAR_FILE
ln -s $(basename $SDL_DIR) SDL
echo

# create template build directory
echo "Creating template build directory"
touch stub.c
$SDL_DIR/build-scripts/create-android-project.py $PACKAGE_NAME stub.c
rm stub.c
echo

# extract SDL3_ttf source code to build dir
echo "Extractng $SDL_TTF_TAR_FILE"
cd $BUILD_DIR/app/jni
tar -xf $TOP/setup_files/$SDL_TTF_TAR_FILE
echo

# download external SDL3_ttf packages
echo "Downloading external SDL3_ttf required packages"
cd $SDL_TTF_DIR/external
./download.sh
echo

# update files in $BUILD_DIR
echo "Updating files in $BUILD_DIR"
mkdir $TOP/setup_files/orig
cd $BUILD_DIR
update_build_file gradle.properties                gradle.properties
update_build_file app_build.gradle                 app/build.gradle
update_build_file app_jni_Application.mk           app/jni/Application.mk
update_build_file app_jni_src_Android.mk           app/jni/src/Android.mk
update_build_file app_src_main_AndroidManifest.xml app/src/main/AndroidManifest.xml
update_build_file app_src_main_java_org_libsdl_app_LocationService.java \
                                                   app/src/main/java/org/libsdl/app/LocationService.java
update_build_file app_src_main_java_org_libsdl_app_SDLActivity.java \
                                                   app/src/main/java/org/libsdl/app/SDLActivity.java
echo "- updating app_src_main_res to app/src/main/res"
mv app/src/main/res $TOP/setup_files/orig/app_src_main_res
ln -s $TOP/setup_files/app_src_main_res app/src/main/res
echo

# add symbolic links to the source code
echo "Creating symbolic links to source code"
cd $BUILD_DIR/app/jni/src
rm stub.c
ln -s ../../../../../../../src/ .
ln -s ../../../../../../../picoc/ .
ln -s ../../../../../../../cJSON/ .
echo

# create assets dir, and create symbolic links to assets
echo "Creating assets directory"
cd $BUILD_DIR/app/src/main
ln -s ../../../../../../assets/ .
echo

echo "SETUP COMPLETE"
