#!/bin/bash

update_build_file()
{
  src=$1
  dest=$2

  echo "- updating $src to $dest"
  cp $BUILD_DIR/$dest $TOP/setup_files/${src}.orig
  cp $TOP/setup_files/${src} $BUILD_DIR/$dest 
}

# ######### MAIN ##########

# set variables
PACKAGE_NAME=org.sthaid.ezApp
SDL_VER=SDL3-3.2.20
SDL_TTF_VER=SDL3_ttf-3.2.2

# init more variables
TOP=`pwd`
SDL_DIR=$TOP/$SDL_VER
SDL_TTF_DIR=$SDL_DIR/build/$PACKAGE_NAME/app/jni/$SDL_TTF_VER
SDL_TAR_FILE=$SDL_VER.tar.gz
SDL_TTF_TAR_FILE=$SDL_TTF_VER.tar.gz
BUILD_DIR=$SDL_DIR/build/$PACKAGE_NAME
RES_DIR=$BUILD_DIR/app/src/main/res

# remove existing SDL directory tree
echo "Remove existing $SDL_DIR"
rm -rf $SDL_DIR
rm -f SDL

# if SDL src tar files are not in the setup_files dir, then download them
if [ ! -f setup_files/$SDL_TAR_FILE -o ! -f setup_files/SDL_TTF_TAR_FILE ]; then
  echo "Downloading SDL3 source tar files"
  cd setup_files
  ./do_get_sdl3_src
  cd ..
fi

# extract the SDL3 src from tar file
echo "Extracting $SDL_TAR_FILE"
tar -xf setup_files/$SDL_TAR_FILE
ln -s $(basename $SDL_DIR) SDL
echo

# create template build directory
echo "Creating template build directory"
touch stub.c
$SDL_DIR/build-scripts/create-android-project.py $PACKAGE_NAME stub.c
rm stub.c
echo

# extract SDL3_ttf source code to build dir
echo "Extractng $SDL_TTF_TAR_FILE"
cd $BUILD_DIR/app/jni
tar -xf $TOP/setup_files/$SDL_TTF_TAR_FILE
echo

# download external SDL3_ttf packages
echo "Downloading external SDL3_ttf required packages"
cd $SDL_TTF_DIR/external
./download.sh
echo

# update some build files in $BUILD_DIR
echo "Updating files in $BUILD_DIR"
cd $BUILD_DIR
update_build_file app_jni_Application.mk app/jni/Application.mk
update_build_file app_build.gradle app/build.gradle
update_build_file app_jni_src_Android.mk app/jni/src/Android.mk
update_build_file app_src_main_res_values_strings.xml app/src/main/res/values/strings.xml
update_build_file app_src_main_AndroidManifest.xml app/src/main/AndroidManifest.xml
echo

# add symbolic links to the source code
echo "Creating symbolic links to source code"
cd $BUILD_DIR/app/jni/src
rm stub.c
ln -s ../../../../../../../src/ .
ln -s ../../../../../../../picoc/ .
echo

# create assets dir, and create symbolic links to assets
echo "Creating assets directory"
cd $BUILD_DIR/app/src/main
ln -s ../../../../../../assets/ .
echo

# create the launcher icon
# xxx update to SDL3
if false; then
echo "Creating launcher icons"
cd $TOP/setup_files
gcc -Wall -g `sdl2-config --cflags` -o create_ic_launcher create_ic_launcher.c -lSDL3 -lSDL2_ttf -lpng
./create_ic_launcher  $RES_DIR/mipmap-mdpi/ic_launcher.png      48
./create_ic_launcher  $RES_DIR/mipmap-hdpi/ic_launcher.png      72
./create_ic_launcher  $RES_DIR/mipmap-xhdpi/ic_launcher.png     96
./create_ic_launcher  $RES_DIR/mipmap-xxhdpi/ic_launcher.png   144
./create_ic_launcher  $RES_DIR/mipmap-xxxhdpi/ic_launcher.png  192
#xxx ./create_ic_launcher  google_play_store/icon_512x512.png        512
rm create_ic_launcher
echo
else
echo "xxx Skipping launcher iconds"
fi

echo "SETUP COMPLETE"
