#!/bin/bash

update_build_file()
{
  src=$1
  dest=$2

  echo "- updating $src to $dest"
  cp $BUILD/$dest $TOP/setup_files/${src}.orig
  cp $TOP/setup_files/${src} $BUILD/$dest 
}

# ######### MAIN ##########

# set directory variables
PACKAGE_NAME=org.sthaid.qne2
TOP=`pwd`
SDL_DIR=$TOP/SDL2
BUILD=$SDL_DIR/build/$PACKAGE_NAME
RES_PATH=$BUILD/app/src/main/res

# if SDL_DIR exists it must be removed
if [ -d $SDL_DIR ]; then
  echo "Remove existing $SDL_DIR"
  rm -rf $SDL_DIR
fi

# extract the SDL2 src from tar file
echo "Extracting SDL2.tar.gz"
tar -xf setup_files/SDL2.tar.gz
echo

# create template build directory
echo "Creating template build directory"
touch stub.c
$SDL_DIR/build-scripts/androidbuild.sh $PACKAGE_NAME stub.c
rm stub.c
echo

# extract SDL2_ttf source code to build dir
echo "Extractng SDL2_ttf-2.0.18.tar.gz"
cd $BUILD/app/jni
tar -xf $TOP/setup_files/SDL2_ttf-2.0.18.tar.gz
echo

# update some build files in $BUILD
echo "Updating files in $BUILD"
update_build_file app_jni_src_Android.mk app/jni/src/Android.mk
update_build_file app_src_main_res_values_strings.xml app/src/main/res/values/strings.xml
update_build_file app_src_main_AndroidManifest.xml app/src/main/AndroidManifest.xml
echo

# add symbolic links to the source code
echo "Creating symbolic links to source code"
cd $BUILD/app/jni/src
rm stub.c
ln -s ../../../../../../src/main.c .
ln -s ../../../../../../src/sdl.c .
ln -s ../../../../../../src/sdl.h .
ln -s ../../../../../../src/std_hdrs.h .
ln -s ../../../../../../src/utils.c .
ln -s ../../../../../../src/utils.h .
ln -s ../../../../../../../picoc/ .
echo

# create assets dir, and create symbolic links to assets
echo "Creating assets directory"
cd $BUILD/app/src/main
ln -s ../../../../../../assets/ .
echo

# create the launcher icon
echo "Creating launcher icons"
cd $TOP/setup_files
gcc -Wall -g `sdl2-config --cflags` -o create_ic_launcher create_ic_launcher.c -lSDL2 -lSDL2_ttf -lpng
./create_ic_launcher  $RES_PATH/mipmap-mdpi/ic_launcher.png      48
./create_ic_launcher  $RES_PATH/mipmap-hdpi/ic_launcher.png      72
./create_ic_launcher  $RES_PATH/mipmap-xhdpi/ic_launcher.png     96
./create_ic_launcher  $RES_PATH/mipmap-xxhdpi/ic_launcher.png   144
./create_ic_launcher  $RES_PATH/mipmap-xxxhdpi/ic_launcher.png  192
#xxx ./create_ic_launcher  google_play_store/icon_512x512.png        512
rm create_ic_launcher
echo

echo "SETUP COMPLETE"
