#!/bin/bash

# cd to qapps dir
top=$(git rev-parse --show-toplevel)
cd $top/qapps

# create tarfile with contents to xfer to android
cd files
tar --exclude log -cf /tmp/xfer.tar .

# copy the tarfile to android
cat /tmp/xfer.tar | run -w 500000 "cat > ../xfer.tar"
rm -f /tmp/xfer.tar

# on android, remove contents of files, and recreate
run "rm -rf *"
run "tar -xvf ../xfer.tar"
run "rm ../xfer.tar"
run "log_clear"
