#!/bin/bash

TARGET=hello
SRCS=hello.c

CFLAGS="-Wall -Werror -g -I. -I../../.. -I/usr/include/SDL2 -D_REENTRANT"
CFLAGS="$CFLAGS -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function"


gcc -o $TARGET $CFLAGS $SRCS ../../../sdl.c -lSDL2 -lSDL2_ttf -lm
if [ $? -ne 0 ]; then
  exit 1
fi

./hello
#rm hello
