#!/bin/bash

# verify parent directory is 'apps'
parent_dir=$(basename $(dirname $PWD))
if [ "$parent_dir" != apps ]; then
    echo "ERROR: parent_dir must be apps"
    exit 1
fi

# if no args provided then 
#   set filename_lsit to all source files in this directory plus the ../layout file
# else
#   else the filename_list are the args
# endif
if [ "$1" = "" ]; then
  filename_list="*.[ch]"
  # xxx layout should exist
  if [ -f ../layout ]; then
    filename_list="$filename_list ../layout"
  fi
else
  filename_list="$*"
fi

# determine the destination dir (on android), and whether it exists
this_dir="$(basename $PWD)"
android_dir="apps/$this_dir"
android_dir_exists=$(ezsh "if [ ! -d $android_dir ]; then echo NO; else echo YES; fi")

# if the android_dir does not exist then prompt user to create it
if [ "$android_dir_exists" != YES ]; then
  echo "ERROR: android dir $android_dir does not exist"
  read -p "Create y/n? " yn
  if [ "$yn" != y ]; then
    exit 1
  fi
  ezsh "mkdir $android_dir"
fi

# loop over filename_list
for filename in $filename_list; do
  # copy the file to Android
  if [ "$filename" != "../layout" ]; then
    echo "copying to android $android_dir/$filename"
    cat $filename | ezsh "cat > $android_dir/$filename"
  else
    echo "copying to android apps/layout"
    cat ../layout | ezsh "cat > apps/layout"
  fi
done

exit 0
