#!/bin/bash

# xxx add -O2

TARGET=/tmp/ez_$(basename $PWD)
SRCS="$(echo *.c) $QNE_TOP/src/sdl.c $QNE_TOP/src/sdl_audio.c $QNE_TOP/src/utils.c $QNE_TOP/src/logging.c"

# pkgconfig for ttf cflags?
CFLAGS="-Wall -Werror -Wno-unused-result -g -I. -I$QNE_TOP/src $(pkg-config sdl3--cflags)"

gcc -o $TARGET $CFLAGS \
    $SRCS \
   -lSDL3 -lSDL3_ttf -lm

if [ $? -ne 0 ]; then
  exit 1
fi

$TARGET

#rm $TARGET
